"""Stub wrapper around the Azure AI Search client.

See the "Azure AI Search" component in ``.helix/ARCHITECTURE.md``: a hybrid
vector + keyword index storing document chunk embeddings generated by Text
Embedding 3 Large, supporting semantic ranking for RAG retrieval.
"""

from __future__ import annotations

from typing import Any

from app.config import get_settings


class SearchService:
    """Thin wrapper around ``azure.search.documents.aio.SearchClient``."""

    def __init__(self) -> None:
        self._settings = get_settings()
        # TODO: instantiate azure.search.documents.aio.SearchClient using
        # AzureKeyCredential or Managed Identity.
        self._client = None

    async def index_chunks(self, documents: list[dict[str, Any]]) -> list[str]:
        """Upload a batch of document chunks (with embedding vectors) to the index.

        TODO: call ``SearchClient.upload_documents`` and return the assigned
        chunk/document keys.
        """

        raise NotImplementedError("SearchService.index_chunks is not implemented")

    async def hybrid_search(
        self, query_text: str, query_vector: list[float], top_k: int = 5
    ) -> list[dict[str, Any]]:
        """Run a hybrid vector + keyword search and return the top-K chunks.

        TODO: call ``SearchClient.search`` with both ``search_text`` and a
        ``VectorizedQuery`` built from ``query_vector``, returning chunk
        content, source document id, and relevance score for each hit.
        """

        raise NotImplementedError("SearchService.hybrid_search is not implemented")

    async def delete_document_chunks(self, document_id: str) -> None:
        """Remove all indexed chunks belonging to ``document_id``.

        TODO: query for matching chunk keys and call
        ``SearchClient.delete_documents``.
        """

        raise NotImplementedError(
            "SearchService.delete_document_chunks is not implemented"
        )
